### ISSUE TITLE
Specific Anomoly

### ISSUE THREAD

**Issue by nequar** [botengine-de/A-Bot#2]
where do i add "
{
  "SetAnomalyEnabledNamePattern": [
    "Drone Horde",
    "Drone Patrol"
  ]
}
" to make the bot only go to these sites?
tried to add it to bot.config where i have the "safe" bookmark and tried to enter it in the AnomalyEnter.cs but i keeps warping to the top of the list

**Comment by Viir** [comment]
I do not understand where this `SetAnomalyEnabledNamePattern` is coming from.
I do not see such a property being read by the bot.
The properties to read are implemented at: https://github.com/botengine-de/A-Bot/blob/master/src/Sanderling.ABot/Bot/Config.cs

A feature to filter anomalies by name is not implemented yet.

**Comment by emesix** [comment]
You have a Fork that is marked as stable with: select-names-of-anomalies Updated a year ago by Viir

https://github.com/botengine-de/A-Bot/tree/select-names-of-anomalies

I was googling for the same thing and saw your answer ;) BTW would be helpful if it worked :)

**Comment by Viir** [comment]
> You have a Fork that is marked as stable with: select-names-of-anomalies Updated a year ago by Viir
> 
> https://github.com/botengine-de/A-Bot/tree/select-names-of-anomalies

Good, so we already have an implementation to test.
@nequar, what about using the branch linked above and then add the setting for `SetAnomalyEnabledNamePattern` to bot.config? Do you see any problem with the implementation from https://github.com/botengine-de/A-Bot/tree/select-names-of-anomalies?

**Comment by SamuelGRwebfab** [comment]
any update on this?

**Comment by Viir** [comment]
Closing this as long as no one is interested.
