### ISSUE TITLE
movement logic

### ISSUE THREAD

**Issue by ButterMeWaffle** [botengine-de/A-Bot#4]
Is the bot supposed to move once in a site? I tested it with a rookie ship on a new toon and it did go into a site and started shooting but didnt seem to care about the range of the enemy (was outside of guns) and didnt move at all. Is this normal behavior or did something go wrong?

also, is  there any way to set it up so it knows to orbit something or even drop a can to orbit?

**Comment by Viir** [comment]
The bot does not contain code to move in an anomaly.

Regarding the orbiting: As far as I understand the discussions on the forum, some people made an orbiting version of A-Bot: http://forum.botengine.de

For an orbiting version, you also might want to look at the repository at https://github.com/Fuzzied/A-Bot-ORBIT-Player-Detection

**Comment by ButterMeWaffle** [comment]
Thanks for the info. I made a fork of your project and im trying to edit it to my needs but I am new to c# and have run into some issues. So i know that i can debug the abot.exe project in the solution. I can also build it to create a real .exe file. awesome. However the combat.cs file which i need to edit is inside of the abot folder (not .exe) and i cant figure out how to edit the code in there, get it to the .exe folder, then build the new code (and get a .exe i can run). 

I imagine I am missing a rather important step here. If what I have said makes sense, would you happen to know the answer to it? Again im brand new to c#, but not to coding in general. So the code makes sense, I just dont understand how to build it properly

**Comment by Viir** [comment]
> Again im brand new to c#, but not to coding in general. So the code makes sense, I just dont understand how to build it properly

For building from source code, use [Visual Studio](https://www.visualstudio.com) (Visual Studio is not Visual Studio Code) 2017.
For building from source code, the requirements stated in the Sanderling Readme also apply to A-Bot. You can find them at https://github.com/Arcitectus/Sanderling#requirements and https://github.com/Arcitectus/Sanderling#building-from-source

There is also a forum thread with information on building A-Bot for someone not familiar with visual studio at http://forum.botengine.de/t/fuzzy-building-a-bot/420

**Comment by ButterMeWaffle** [comment]
Thanks! Ill have a look at those
