### ISSUE TITLE
Local Only Bot

### ISSUE THREAD

**Issue by ghost** [botengine-de/A-Bot#5]
It looks like your bot detects entries into local.
Can you separate that module and just make a bot which watches local and pings (message or visual alert) if anyone enters?

Would be really useful.

**Comment by Viir** [comment]
> Can you separate that module and just make a bot which watches local and pings (message or visual alert) if anyone enters?

Sure, have a look at the example at http://forum.botengine.de/t/eve-online-anomaly-ratting-bot-release/87/294?u=viir

To quote from there:

> I have this code
> [....]
> It beeps when a neutral enters the "location."

Use the code in the Sanderling IDE from https://github.com/Arcitectus/Sanderling/releases

**Comment by ghost** [comment]
Thanks I saw this code. Is there any chance of it being expanded to do things like post to slack and/or a post a visual dialogue box message? 

Although the sound alert alone is fantastic.

Edit: can multiple Sanderling exes be opened at once to run this script on multiple clients?

**Comment by Viir** [comment]
> Is there any chance of it being expanded to do things like post to slack and/or a post a visual dialogue box message?

For posting to slack channels, I would try the slack webhooks interface: https://api.slack.com/incoming-webhooks

For displaying a visual dialogue box message from the Sanderling IDE, I found a code example in the forum at http://forum.botengine.de/t/how-to-show-popup-window/52/2?u=viir

This is the code for displaying a visual dialogue box message, still works with latest version:
```c#
#r "System.Windows.Forms"
System.Windows.Forms.MessageBox.Show("My message here");
```

**Comment by Viir** [comment]
> Edit: can multiple Sanderling exes be opened at once to run this script on multiple clients?

Yes, a guide on how to configure the association between sanderling instances and eve online client instances can be found at http://forum.botengine.de/t/multi-instances-support/326/3?u=viir

**Comment by Andrey5Ka** [comment]
I use bot, but it  don't work and wtite me:
2 leaves:
Diagnostic: "warning: no configuration supplied."(BotTask->BotTask->DiagnosticTask)
Diagnostic: "no suitable anomaly found. waiting for anomaly to appear."(BotTask->AnomalyEnter->DiagnosticTask)

**Comment by Viir** [comment]
Closing this as the question was answered.

**Comment by Viir** [comment]
@Andrey5Ka, the bot is only for anomaly ratting. As long as there is no anomaly, there is nothing to do for the bot.
