### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by blue2you** [botengine-de/A-Bot#6]
I have downloaded 17.05.03.Sanderling.ABot.exe on windows 7 Ultimate 64 bit with service pack 1. However the bot doesnt run. Every time I run it I get "Sanderling.ABot.exe has stopped working" can you help me with this please.

**Comment by Viir** [comment]
Looks like the readme needs some more info on requirements:

The application requires Microsoft .NET Framework 4.6.1 which can be downloaded from https://www.microsoft.com/download/details.aspx?id=49982.

Does it run on your system when Microsoft .NET Framework 4.6.1 is installed?
