### ISSUE TITLE
orbiting in anoms

### ISSUE THREAD

**Issue by JustBigDave** [botengine-de/A-Bot#7]
hey is there a way of getting a ship to orbit and activate a speed module in the bot ty

**Comment by Viir** [comment]
Looks like some people already made an orbiting version. Have a look at the forum topic at http://forum.botengine.de/t/fuzzy-building-a-bot/420/112?u=viir

Also, for orbiting, there is the repository at https://github.com/Fuzzied/A-Bot-ORBIT-Player-Detection/commit/cd0428fe8a2a772ae1aa679b7812c8b5b4e623f0
