### ISSUE TITLE
save ship

### ISSUE THREAD

**Issue by boppie** [botengine-de/A-Bot#8]
It never warps out when trying to "save ship" it just clicks on sun next to system name

**Comment by Viir** [comment]
To set up the bot to save the ship, you need to configure the name of the bookmark for the safespot. Use the format as follows and write this to a file named "bot.config" and locate it in the directory with the bot executable file:
```json
{
  "RetreatBookmark": "name of your bookmark as it appears in the list items in solar system menu"
}
```

I found this at http://forum.botengine.de/t/eve-online-anomaly-ratting-bot-release/87/29?u=viir
